### ISSUE TITLE
使用自有图片视角检查报错

### ISSUE THREAD

**Issue by lzran** [AiuniAI/Unique3D#100]
为什么我使用自有图片就会报视角检查错误呢，具体错误信息：Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/Unique3D/./app/gradio_3dgen.py", line 21, in generate3dv2
    new_meshes = geo_reconstruct(rgb_pils, None, front_pil, do_refine=do_refine, predict_normal=True, expansion_weight=expansion_weight, init_type=init_type)
  File "/root/autodl-tmp/Unique3D/./scripts/multiview_inference.py", line 90, in geo_reconstruct
    _ = multiview_color_projection(meshes, rgb_pils, resolution=512, device="cuda", complete_unseen=False, confidence_threshold=0.1)    # just check for validation, may throw error
  File "/root/autodl-tmp/Unique3D/./scripts/project_mesh.py", line 284, in multiview_color_projection
    ret = project_color(meshes, camera, image, eps=eps, resolution=resolution, device=device, use_alpha=use_alpha)
  File "/root/autodl-tmp/Unique3D/./scripts/project_mesh.py", line 143, in project_color
    assert cos_angles.mean() < 0, f"The view direction is not correct. cos_angles.mean()={cos_angles.mean()}"
AssertionError: The view direction is not correct. cos_angles.mean()=0.18529796600341797
![图片3](https://github.com/user-attachments/assets/2609367f-a5ad-4525-9074-01251b14afa6)
这是原图

**Comment by xujiamingtxwd123** [comment]
一样的错误
