### ISSUE TITLE
about diffusers-0.27.2 plz！！！The third day of failed installation

### ISSUE THREAD

**Issue by DamienCz** [AiuniAI/Unique3D#51]
I found that the automatically downloaded pytorch3D0.7.7 could not be adapted to py10/11. I finally manually downloaded 0.7.5 to solve this problem, but I couldn't solve the subsequent diffuses problem. I tried to switch various versions and the same error message appeared.  plz！！！！！
 

info：
(unique3d-py310) E:\Unique3D>python gradio_app.py --port 7860
Traceback (most recent call last):
  File "E:\Unique3D\gradio_app.py", line 14, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "E:\Unique3D\app\gradio_3dgen.py", line 7, in <module>
    from app.custom_models.mvimg_prediction import run_mvprediction
  File "E:\Unique3D\app\custom_models\mvimg_prediction.py", line 8, in <module>
    from app.custom_models.utils import load_pipeline
  File "E:\Unique3D\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "E:\Unique3D\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "E:\Unique3D\custum_3d_diffusion\trainings\base.py", line 14, in <module>
    from custum_3d_diffusion.custum_modules.unifield_processor import ConfigurableUNet2DConditionModel, AttnConfig
  File "E:\Unique3D\custum_3d_diffusion\custum_modules\unifield_processor.py", line 8, in <module>
    from diffusers.loaders import IPAdapterMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (C:\Users\WS01\anaconda3\envs\unique3d-py310\lib\site-packages\diffusers\loaders\__init__.py)

(unique3d-py310) E:\Unique3D>

(unique3d-py310) E:\Unique3D>python test_3d.py
Python executable: C:\Users\WS01\anaconda3\envs\unique3d-py310\python.exe
Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Sys path: ['E:\\Unique3D', 'E:\\Unique3D\\pytorch3d-0.7.5', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310\\lib\\site-packages\\diffusers\\loaders', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310\\python310.zip', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310\\DLLs', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310\\lib', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310', 'C:\\Users\\WS01\\anaconda3\\envs\\unique3d-py310\\lib\\site-packages']
PYTHONPATH: E:\Unique3D\pytorch3d-0.7.5;C:\Users\WS01\anaconda3\envs\unique3d-py310\lib\site-packages\diffusers\loaders
PyTorch3D imported successfully.

**Comment by hcsper** [comment]
I'm having the same issue,  ask if you solved it
**"ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"**

**Comment by DamienCz** [comment]
> I'm having the same issue, ask if you solved it **"ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"**

I was met it but solved it in comfyui

**Comment by hcsper** [comment]
> > I'm having the same issue, ask if you solved it **"ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"**
> 
> I was met it but solved it in comfyui

Wow, can you tell us the way?thanks

**Comment by DamienCz** [comment]
> > > I'm having the same issue, ask if you solved it **"ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"**
> > 
> > 
> > I was met it but solved it in comfyui
> 
> Wow, can you tell us the way?thanks

I really want to help u guys but actucaully ,i dont know ........

**Comment by CorvaeOboro** [comment]
"ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"

in the ```diffusers/loaders/__init__.py```  , it has conditions for importing modules by ```is_torch_available()``` and ```is_transformers_available()``` . IPAdapterMixin is only imported if both conditions are met .

SOLUTION = install transformers
```pip install transformers==4.39.3```

**Comment by hcsper** [comment]
> "ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders'"
> 
> in the `diffusers/loaders/__init__.py` , it has conditions for importing modules by `is_torch_available()` and `is_transformers_available()` . IPAdapterMixin is only imported if both conditions are met .
> 
> SOLUTION = install transformers `pip install transformers==4.39.3`

thanks very much! This problem has been solved, but there is a new problem,  can you run successfully, normal reasoning?
