### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by rockyyee** [AiuniAI/Unique3D#65]
I'am a amateur. Why I don't have 'app/graodio_local.py' this file?    Do I need to create my own?   If that's the case, why isn't `pip install gradio` this one installation instruction in the tutorial?

**Comment by rockyyee** [comment]
When I 'pip install gradio' finishes I try running
`python app\gradio_local.py --port 7860`

`import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)
`

which gives this error:
`gradio  ....... ReadTimeout: timed out`
you need to odify Installation position:
`pip install https://gradio-builds.s3.amazonaws.com/aae46d9199e1edc8a22c96aba1ade12f6ebc1da1/gradio-4.21.0-py3-none-any.whl
`

**Comment by rockyyee** [comment]
emm...No module named 'pytorch3d
`$ python app/gradio_local.py --port 7860`
```
Traceback (most recent call last):
  File "G:\Program Data\anaconda3\envs\unique3d-py311\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "G:\Program Data\anaconda3\envs\unique3d-py311\app\gradio_3dgen.py", line 4, in <module>
    from pytorch3d.structures import Meshes
ModuleNotFoundError: No module named 'pytorch3d'
```

**Comment by wukailu** [comment]
You can refer to https://github.com/AiuniAI/Unique3D?tab=readme-ov-file#preparation-for-inference to install the required environment for inference.

**Comment by trueices** [comment]
no need to create your own.
https://github.com/oak-barry/Unique3D
this is more helpful.

**Comment by GeniusAdonis** [comment]
I think it is one of clones of the original version.

**Comment by trueices** [comment]
yep, difference in the Readme file and requirements file and it describes how to install in your local in more detail.
