### ISSUE TITLE
OpenGL MUST BE 4.4 later？

### ISSUE THREAD

**Issue by jimmyyuzhiqiu** [AiuniAI/Unique3D#76]
Hi!I encountered a RuntimeError indicating that OpenGL 4.4 or later is required, but MY current setup only supports OpenGL 4.2.
Here is my environment:
`(unique3d-env) DESKTOP-LAE2LNC% glxinfo | grep "OpenGL version"

OpenGL version string: 4.2 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2`
And here is my error:
`Traceback (most recent call last):
  File "/home/jimmyyuzhiqiu/Unique3D/app/gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "/home/jimmyyuzhiqiu/Unique3D/./app/gradio_3dgen.py", line 10, in <module>
    from scripts.multiview_inference import geo_reconstruct
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/multiview_inference.py", line 4, in <module>
    from scripts.project_mesh import multiview_color_projection
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
  File "/home/jimmyyuzhiqiu/.pyenv/versions/unique3d-env/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 133, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
RuntimeError: OpenGL 4.4 or later is required`

**Comment by jimmyyuzhiqiu** [comment]
Is this the problem of my window11 problem? But I can't find download in win11 ,only in win10 .Or should I try to upgrade OpenGL in wsl2?

**Comment by wukailu** [comment]
We recommend upgrading the OpenGL version or just replacing ***all*** dr.RasterizeGLContext with dr.RasterizeCudaContext (it will be a bit slower, but no longer depends on OpenGL).

**Comment by jimmyyuzhiqiu** [comment]
Thank you for your reply ,I actually tried this before. But I find this error,could u tell me what to do next？:Traceback (most recent call last):
  File "/home/jimmyyuzhiqiu/Unique3D/app/gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "/home/jimmyyuzhiqiu/Unique3D/./app/gradio_3dgen.py", line 10, in <module>
    from scripts.multiview_inference import geo_reconstruct
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/multiview_inference.py", line 4, in <module>
    from scripts.project_mesh import multiview_color_projection
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeCudaContext(output_db=False, device=device)
TypeError: RasterizeCudaContext.__init__() got an unexpected keyword argument 'output_db'

**Comment by jimmyyuzhiqiu** [comment]
Do I need to delete all the 'output_db'?

**Comment by jimmyyuzhiqiu** [comment]
I still can't deal with this problem,after I delete all the 'output_db'.Now I can't even find this code"class Pix2FacesRenderer:
    def __init__(self, device="cuda"):
        self._glctx = dr.RasterizeCudaContext(device=device)
        self.device = device
        _warmup(self._glctx, device)"

.:"Traceback (most recent call last):
  File "/home/jimmyyuzhiqiu/Unique3D/app/gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "/home/jimmyyuzhiqiu/Unique3D/./app/gradio_3dgen.py", line 10, in <module>
    from scripts.multiview_inference import geo_reconstruct
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/multiview_inference.py", line 4, in <module>
    from scripts.project_mesh import multiview_color_projection
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
  File "/home/jimmyyuzhiqiu/Unique3D/./scripts/project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeCudaContext(output_db=False, device=device)
TypeError: RasterizeCudaContext.__init__() got an unexpected keyword argument 'output_db'
(unique3d-env) DESKTOP-LAE2LNC% "
