### ISSUE TITLE
运行python app/gradio_local.py --port 7860报错，请问是什么问题?

### ISSUE THREAD

**Issue by sherwoodwoo** [AiuniAI/Unique3D#87]
G:\Unique3D>E:\anaconda3\envs\unique3d-py311\python.exe app/gradio_local.py --port 7860
Traceback (most recent call last):
  File "G:\Unique3D\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "G:\Unique3D\app\gradio_3dgen.py", line 6, in <module>
    from app.custom_models.mvimg_prediction import run_mvprediction
  File "G:\Unique3D\app\custom_models\mvimg_prediction.py", line 8, in <module>
    from app.custom_models.utils import load_pipeline
  File "G:\Unique3D\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "G:\Unique3D\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "G:\Unique3D\custum_3d_diffusion\trainings\base.py", line 11, in <module>
    import wandb
  File "E:\anaconda3\envs\unique3d-py311\Lib\site-packages\wandb\__init__.py", line 37, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "E:\anaconda3\envs\unique3d-py311\Lib\site-packages\wandb\apis\__init__.py", line 6, in <module>
    from gql.client import RetryError
ImportError: cannot import name 'RetryError' from 'gql.client' (E:\anaconda3\envs\unique3d-py311\Lib\site-packages\gql\client.py)

最后一步报错了.

**Comment by sherwoodwoo** [comment]
uninstall & reinstall wandb
